"""add missing log_entry columns

Revision ID: d48fdf5a2eb0
Revises: f1e5f9d61493
Create Date: 2026-02-28 20:31:17.435756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd48fdf5a2eb0'
down_revision = 'f1e5f9d61493'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('log_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('department', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('location', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('protocol', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('request_method', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('server_ip', sa.String(length=45), nullable=True))
        batch_op.add_column(sa.Column('response_size', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('request_size', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('status_code', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('content_type', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('user_agent', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('threat_name', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('threat_class', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('threat_category', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('threat_severity', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('file_type', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('file_class', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('log_entries', schema=None) as batch_op:
        batch_op.drop_column('file_class')
        batch_op.drop_column('file_type')
        batch_op.drop_column('threat_severity')
        batch_op.drop_column('threat_category')
        batch_op.drop_column('threat_class')
        batch_op.drop_column('threat_name')
        batch_op.drop_column('user_agent')
        batch_op.drop_column('content_type')
        batch_op.drop_column('status_code')
        batch_op.drop_column('request_size')
        batch_op.drop_column('response_size')
        batch_op.drop_column('server_ip')
        batch_op.drop_column('request_method')
        batch_op.drop_column('protocol')
        batch_op.drop_column('location')
        batch_op.drop_column('department')

    # ### end Alembic commands ###
