"""initial

Revision ID: f1e5f9d61493
Revises: 
Create Date: 2026-02-27 19:57:10.372934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1e5f9d61493'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('log_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_filename', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('file_type', sa.String(length=10), nullable=False),
    sa.Column('entry_count', sa.Integer(), nullable=True),
    sa.Column('upload_status', sa.String(length=20), nullable=True),
    sa.Column('analysis_status', sa.String(length=20), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('log_files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_log_files_user_id'), ['user_id'], unique=False)

    op.create_table('log_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('log_file_id', sa.Integer(), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('source_ip', sa.String(length=45), nullable=True),
    sa.Column('destination_url', sa.Text(), nullable=True),
    sa.Column('user', sa.String(length=120), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.Column('bytes_transferred', sa.BigInteger(), nullable=True),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('raw_line', sa.Text(), nullable=False),
    sa.Column('is_anomalous', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['log_file_id'], ['log_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('log_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_log_entries_is_anomalous'), ['is_anomalous'], unique=False)
        batch_op.create_index(batch_op.f('ix_log_entries_log_file_id'), ['log_file_id'], unique=False)

    op.create_table('analysis_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('log_file_id', sa.Integer(), nullable=False),
    sa.Column('log_entry_id', sa.Integer(), nullable=True),
    sa.Column('anomaly_type', sa.String(length=100), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['log_entry_id'], ['log_entries.id'], ),
    sa.ForeignKeyConstraint(['log_file_id'], ['log_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analysis_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analysis_results_log_entry_id'), ['log_entry_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_analysis_results_log_file_id'), ['log_file_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analysis_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analysis_results_log_file_id'))
        batch_op.drop_index(batch_op.f('ix_analysis_results_log_entry_id'))

    op.drop_table('analysis_results')
    with op.batch_alter_table('log_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_log_entries_log_file_id'))
        batch_op.drop_index(batch_op.f('ix_log_entries_is_anomalous'))

    op.drop_table('log_entries')
    with op.batch_alter_table('log_files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_log_files_user_id'))

    op.drop_table('log_files')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
